BEGIN;

-- =========================================================
-- Item Comercial vNext (fase 1)
-- Objetivo:
--   - abrir capa comercial nueva sin tocar snapshots/cron vigentes
--   - mantener el stock real en orígenes técnicos
--   - soportar Items Comerciales, Envases, Etiqueta y Paquetería
-- Compatibilidad asumida con snapshot actual:
--   - app.item_seguimiento.item_id         :: bigint
--   - app.cost_option.cost_option_id       :: bigint
--   - app.item_formulado.item_formulado_id :: integer
--   - unidades internas oficiales          :: GR | ML | UN
-- =========================================================

CREATE TABLE IF NOT EXISTS app.item_comercial (
  item_comercial_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text,
  cantidad numeric NOT NULL,
  unidad text NOT NULL,
  proveedor_item_id bigint,
  manual_cost_option_id bigint,
  formulado_item_formulado_id integer,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT item_comercial_unidad_chk
    CHECK (unidad IN ('GR', 'ML', 'UN')),
  CONSTRAINT item_comercial_cantidad_chk
    CHECK (cantidad > 0),
  CONSTRAINT item_comercial_un_entera_chk
    CHECK (unidad <> 'UN' OR cantidad = trunc(cantidad)),
  CONSTRAINT item_comercial_origen_unico_chk
    CHECK (
      ((proveedor_item_id IS NOT NULL)::int +
       (manual_cost_option_id IS NOT NULL)::int +
       (formulado_item_formulado_id IS NOT NULL)::int) = 1
    ),
  CONSTRAINT item_comercial_proveedor_fk
    FOREIGN KEY (proveedor_item_id)
    REFERENCES app.item_seguimiento(item_id)
    ON DELETE RESTRICT,
  CONSTRAINT item_comercial_manual_fk
    FOREIGN KEY (manual_cost_option_id)
    REFERENCES app.cost_option(cost_option_id)
    ON DELETE RESTRICT,
  CONSTRAINT item_comercial_formulado_fk
    FOREIGN KEY (formulado_item_formulado_id)
    REFERENCES app.item_formulado(item_formulado_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_item_comercial_proveedor_item_id
  ON app.item_comercial(proveedor_item_id)
  WHERE proveedor_item_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_comercial_manual_cost_option_id
  ON app.item_comercial(manual_cost_option_id)
  WHERE manual_cost_option_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_comercial_formulado_item_formulado_id
  ON app.item_comercial(formulado_item_formulado_id)
  WHERE formulado_item_formulado_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_comercial_activo_nombre
  ON app.item_comercial(activo, nombre);


CREATE TABLE IF NOT EXISTS app.item_envase (
  item_envase_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text,
  proveedor_item_id bigint,
  manual_cost_option_id bigint,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT item_envase_origen_unico_chk
    CHECK (
      ((proveedor_item_id IS NOT NULL)::int +
       (manual_cost_option_id IS NOT NULL)::int) = 1
    ),
  CONSTRAINT item_envase_proveedor_fk
    FOREIGN KEY (proveedor_item_id)
    REFERENCES app.item_seguimiento(item_id)
    ON DELETE RESTRICT,
  CONSTRAINT item_envase_manual_fk
    FOREIGN KEY (manual_cost_option_id)
    REFERENCES app.cost_option(cost_option_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_item_envase_proveedor_item_id
  ON app.item_envase(proveedor_item_id)
  WHERE proveedor_item_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_envase_manual_cost_option_id
  ON app.item_envase(manual_cost_option_id)
  WHERE manual_cost_option_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_envase_activo_nombre
  ON app.item_envase(activo, nombre);


CREATE TABLE IF NOT EXISTS app.item_etiqueta (
  item_etiqueta_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  material text,
  medidas text NOT NULL,
  descripcion text,
  proveedor_item_id bigint,
  manual_cost_option_id bigint,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT item_etiqueta_medidas_chk
    CHECK (length(trim(medidas)) > 0),
  CONSTRAINT item_etiqueta_origen_unico_chk
    CHECK (
      ((proveedor_item_id IS NOT NULL)::int +
       (manual_cost_option_id IS NOT NULL)::int) = 1
    ),
  CONSTRAINT item_etiqueta_proveedor_fk
    FOREIGN KEY (proveedor_item_id)
    REFERENCES app.item_seguimiento(item_id)
    ON DELETE RESTRICT,
  CONSTRAINT item_etiqueta_manual_fk
    FOREIGN KEY (manual_cost_option_id)
    REFERENCES app.cost_option(cost_option_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_item_etiqueta_proveedor_item_id
  ON app.item_etiqueta(proveedor_item_id)
  WHERE proveedor_item_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_etiqueta_manual_cost_option_id
  ON app.item_etiqueta(manual_cost_option_id)
  WHERE manual_cost_option_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_etiqueta_activo_nombre
  ON app.item_etiqueta(activo, nombre);


CREATE TABLE IF NOT EXISTS app.item_paqueteria (
  item_paqueteria_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text,
  proveedor_item_id bigint,
  manual_cost_option_id bigint,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT item_paqueteria_origen_unico_chk
    CHECK (
      ((proveedor_item_id IS NOT NULL)::int +
       (manual_cost_option_id IS NOT NULL)::int) = 1
    ),
  CONSTRAINT item_paqueteria_proveedor_fk
    FOREIGN KEY (proveedor_item_id)
    REFERENCES app.item_seguimiento(item_id)
    ON DELETE RESTRICT,
  CONSTRAINT item_paqueteria_manual_fk
    FOREIGN KEY (manual_cost_option_id)
    REFERENCES app.cost_option(cost_option_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_item_paqueteria_proveedor_item_id
  ON app.item_paqueteria(proveedor_item_id)
  WHERE proveedor_item_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_paqueteria_manual_cost_option_id
  ON app.item_paqueteria(manual_cost_option_id)
  WHERE manual_cost_option_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_item_paqueteria_activo_nombre
  ON app.item_paqueteria(activo, nombre);


CREATE TABLE IF NOT EXISTS app.item_comercial_envase (
  item_comercial_envase_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_comercial_id bigint NOT NULL,
  item_envase_id bigint NOT NULL,
  cantidad numeric NOT NULL,
  obligatorio boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT item_comercial_envase_cantidad_chk
    CHECK (cantidad > 0),
  CONSTRAINT item_comercial_envase_fk
    FOREIGN KEY (item_comercial_id)
    REFERENCES app.item_comercial(item_comercial_id)
    ON DELETE CASCADE,
  CONSTRAINT item_comercial_envase_item_fk
    FOREIGN KEY (item_envase_id)
    REFERENCES app.item_envase(item_envase_id)
    ON DELETE RESTRICT,
  CONSTRAINT item_comercial_envase_unique
    UNIQUE (item_comercial_id, item_envase_id)
);

CREATE INDEX IF NOT EXISTS idx_item_comercial_envase_item_comercial_id
  ON app.item_comercial_envase(item_comercial_id);

CREATE INDEX IF NOT EXISTS idx_item_comercial_envase_item_envase_id
  ON app.item_comercial_envase(item_envase_id);


CREATE TABLE IF NOT EXISTS app.item_comercial_etiqueta (
  item_comercial_etiqueta_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_comercial_id bigint NOT NULL,
  item_etiqueta_id bigint NOT NULL,
  cantidad numeric NOT NULL,
  obligatorio boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT item_comercial_etiqueta_cantidad_chk
    CHECK (cantidad > 0),
  CONSTRAINT item_comercial_etiqueta_fk
    FOREIGN KEY (item_comercial_id)
    REFERENCES app.item_comercial(item_comercial_id)
    ON DELETE CASCADE,
  CONSTRAINT item_comercial_etiqueta_item_fk
    FOREIGN KEY (item_etiqueta_id)
    REFERENCES app.item_etiqueta(item_etiqueta_id)
    ON DELETE RESTRICT,
  CONSTRAINT item_comercial_etiqueta_unique
    UNIQUE (item_comercial_id, item_etiqueta_id)
);

CREATE INDEX IF NOT EXISTS idx_item_comercial_etiqueta_item_comercial_id
  ON app.item_comercial_etiqueta(item_comercial_id);

CREATE INDEX IF NOT EXISTS idx_item_comercial_etiqueta_item_etiqueta_id
  ON app.item_comercial_etiqueta(item_etiqueta_id);

COMMIT;
