-- Propuesta SQL mínima vNext para capa comercial nueva
-- Estado: propuesta documental. No aplicada.
-- Objetivo: habilitar Items Comerciales con origen técnico único y catálogos operativos.

create table if not exists app.item_comercial (
  item_comercial_id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  cantidad numeric(18,6) not null,
  unidad text not null,
  proveedor_item_id bigint,
  manual_cost_option_id bigint,
  formulado_item_formulado_id bigint,
  activo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint item_comercial_unidad_chk
    check (unidad in ('GR','ML','UN')),
  constraint item_comercial_cantidad_pos_chk
    check (cantidad > 0),
  constraint item_comercial_un_entera_chk
    check (unidad <> 'UN' or cantidad = trunc(cantidad)),
  constraint item_comercial_origen_unico_chk
    check (
      ((proveedor_item_id is not null)::int +
       (manual_cost_option_id is not null)::int +
       (formulado_item_formulado_id is not null)::int) = 1
    ),
  constraint item_comercial_proveedor_fk
    foreign key (proveedor_item_id) references app.item_seguimiento(item_id),
  constraint item_comercial_manual_fk
    foreign key (manual_cost_option_id) references app.cost_option(cost_option_id),
  constraint item_comercial_formulado_fk
    foreign key (formulado_item_formulado_id) references app.item_formulado(item_formulado_id)
);

create index if not exists idx_item_comercial_proveedor_item_id
  on app.item_comercial (proveedor_item_id)
  where proveedor_item_id is not null;
create index if not exists idx_item_comercial_manual_cost_option_id
  on app.item_comercial (manual_cost_option_id)
  where manual_cost_option_id is not null;
create index if not exists idx_item_comercial_formulado_item_formulado_id
  on app.item_comercial (formulado_item_formulado_id)
  where formulado_item_formulado_id is not null;
create index if not exists idx_item_comercial_activo_updated
  on app.item_comercial (activo, updated_at desc);

create table if not exists app.item_envase (
  item_envase_id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  proveedor_item_id bigint,
  manual_cost_option_id bigint,
  activo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint item_envase_origen_unico_chk
    check (((proveedor_item_id is not null)::int + (manual_cost_option_id is not null)::int) = 1),
  constraint item_envase_proveedor_fk
    foreign key (proveedor_item_id) references app.item_seguimiento(item_id),
  constraint item_envase_manual_fk
    foreign key (manual_cost_option_id) references app.cost_option(cost_option_id)
);
create index if not exists idx_item_envase_proveedor_item_id
  on app.item_envase (proveedor_item_id)
  where proveedor_item_id is not null;
create index if not exists idx_item_envase_manual_cost_option_id
  on app.item_envase (manual_cost_option_id)
  where manual_cost_option_id is not null;

create table if not exists app.item_etiqueta (
  item_etiqueta_id bigint generated by default as identity primary key,
  nombre text not null,
  material text,
  medidas text not null,
  descripcion text,
  proveedor_item_id bigint,
  manual_cost_option_id bigint,
  activo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint item_etiqueta_origen_unico_chk
    check (((proveedor_item_id is not null)::int + (manual_cost_option_id is not null)::int) = 1),
  constraint item_etiqueta_medidas_chk
    check (btrim(medidas) <> ''),
  constraint item_etiqueta_proveedor_fk
    foreign key (proveedor_item_id) references app.item_seguimiento(item_id),
  constraint item_etiqueta_manual_fk
    foreign key (manual_cost_option_id) references app.cost_option(cost_option_id)
);
create index if not exists idx_item_etiqueta_proveedor_item_id
  on app.item_etiqueta (proveedor_item_id)
  where proveedor_item_id is not null;
create index if not exists idx_item_etiqueta_manual_cost_option_id
  on app.item_etiqueta (manual_cost_option_id)
  where manual_cost_option_id is not null;

create table if not exists app.item_paqueteria (
  item_paqueteria_id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  proveedor_item_id bigint,
  manual_cost_option_id bigint,
  activo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint item_paqueteria_origen_unico_chk
    check (((proveedor_item_id is not null)::int + (manual_cost_option_id is not null)::int) = 1),
  constraint item_paqueteria_proveedor_fk
    foreign key (proveedor_item_id) references app.item_seguimiento(item_id),
  constraint item_paqueteria_manual_fk
    foreign key (manual_cost_option_id) references app.cost_option(cost_option_id)
);
create index if not exists idx_item_paqueteria_proveedor_item_id
  on app.item_paqueteria (proveedor_item_id)
  where proveedor_item_id is not null;
create index if not exists idx_item_paqueteria_manual_cost_option_id
  on app.item_paqueteria (manual_cost_option_id)
  where manual_cost_option_id is not null;

create table if not exists app.item_comercial_envase (
  item_comercial_envase_id bigint generated by default as identity primary key,
  item_comercial_id bigint not null,
  item_envase_id bigint not null,
  cantidad numeric(18,6) not null,
  obligatorio boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint item_comercial_envase_cantidad_pos_chk
    check (cantidad > 0),
  constraint item_comercial_envase_item_comercial_fk
    foreign key (item_comercial_id) references app.item_comercial(item_comercial_id) on delete cascade,
  constraint item_comercial_envase_item_envase_fk
    foreign key (item_envase_id) references app.item_envase(item_envase_id),
  constraint item_comercial_envase_unique
    unique (item_comercial_id, item_envase_id)
);
create index if not exists idx_item_comercial_envase_item_comercial_id
  on app.item_comercial_envase (item_comercial_id);
create index if not exists idx_item_comercial_envase_item_envase_id
  on app.item_comercial_envase (item_envase_id);

create table if not exists app.item_comercial_etiqueta (
  item_comercial_etiqueta_id bigint generated by default as identity primary key,
  item_comercial_id bigint not null,
  item_etiqueta_id bigint not null,
  cantidad numeric(18,6) not null,
  obligatorio boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint item_comercial_etiqueta_cantidad_pos_chk
    check (cantidad > 0),
  constraint item_comercial_etiqueta_item_comercial_fk
    foreign key (item_comercial_id) references app.item_comercial(item_comercial_id) on delete cascade,
  constraint item_comercial_etiqueta_item_etiqueta_fk
    foreign key (item_etiqueta_id) references app.item_etiqueta(item_etiqueta_id),
  constraint item_comercial_etiqueta_unique
    unique (item_comercial_id, item_etiqueta_id)
);
create index if not exists idx_item_comercial_etiqueta_item_comercial_id
  on app.item_comercial_etiqueta (item_comercial_id);
create index if not exists idx_item_comercial_etiqueta_item_etiqueta_id
  on app.item_comercial_etiqueta (item_etiqueta_id);
